---
# This playbook deploys the Kubernetes cluster with Contrail CNI

# Author: SAVITHRU LOKANATH
# Contact: SAVITHRU AT ICLOUD DOT COM

- name: Apply common configs to all nodes
  hosts: all
  remote_user: root
  roles:
    - common

- name: Deploy kubernetes masters
  hosts: masters
  remote_user: root
  roles:
    - master

- name: Deploy kubernetes nodes
  hosts: nodes
  remote_user: root
  roles:
    - node
