---
# This playbook deploys the Kubernetes cluster with Contrail CNI

# Author: SAVITHRU LOKANATH
# Contact: SAVITHRU AT ICLOUD DOT COM

- name: Register nodes to master
  shell: kubeadm join {{ groups['masters'][0] }}:6443 --token {{ hostvars[groups['masters'][0]]['token'] }}
  tags: node

- name: Launch Contrail Networking
  shell: kubectl apply -f /tmp/contrail-installer.yml
  delegate_to: {{ groups['masters'][0] }}
  tags: node

- name: Launch kubernetes dashboard
  shell: kubectl create -f /tmp/k8s-dashboard.yml
  delegate_to: {{ groups['masters'][0] }}
  tags: node

- name: Info
  debug:
    msg: 
      - "Contrail UI @ https://{{ groups['masters'][0] }}:8413"
      - "Kubernetes UI @ http://{{ groups['nodes'][0] }}:9090"
