---
# This playbook deploys the Kubernetes cluster with Contrail CNI

# Author: SAVITHRU LOKANATH
# Contact: SAVITHRU AT ICLOUD DOT COM

- name: Register nodes to master
  shell: kubeadm join {{ groups['masters'][0] }}:6443 --token {{ hostvars[groups['masters'][0]]['token'] }}
  tags: node

- name: Launch Contrail Networking
  shell: kubectl apply -f /tmp/contrail-installer.yml
  delegate_to: "{{ groups['masters'][0] }}"
  tags: node

- name: Launch kubernetes dashboard
  shell: kubectl create -f /tmp/k8s-dashboard.yml
  delegate_to: "{{ groups['masters'][0] }}"
  tags: node

- name: Get master hostname
  uri:
    url: http://169.254.169.254/latest/meta-data/public-hostname
    return_content: yes
  register: hostname_master 
  delegate_to: "{{ groups['masters'][0] }}"

- name: Get node hostname
  uri:
    url: http://169.254.169.254/latest/meta-data/public-hostname
    return_content: yes
  register: hostname_node

- name: Wait for Contrail dashboard service to come up
  uri:
    url: https://{{ hostname_master.content }}:8143
    validate_certs: False
    status_code: 200
  register: result
  until: result.status == 200
  retries: 300
  delay: 2

- name: Wait for kubernetes dashboard pod to come up
  uri:
    url: http://{{ hostname_node.content }}:9090
    validate_certs: False
    status_code: 200
  register: result
  until: result.status == 200
  retries: 50
  delay: 2

- name: Cluster info
  debug:
    msg: 
      - "Contrail dashboard @ https://{{ hostname_master.content }}:8143"
      - "Kubernetes dashboard @ http://{{ hostname_node.content }}:9090"
      - "Login user: admin"
      - "Login password: contrail123"
      - "Built & Maintained by: Savithru M Lokanath"
      - "Contact: savithru@icloud.com"
