---
# This playbook deploys the Kubernetes cluster with Contrail CNI

# Author: SAVITHRU LOKANATH
# Contact: SAVITHRU AT ICLOUD DOT COM

- name: Update packages
  apt: update_cache=yes

- name: Install base packages
  apt: name={{item}} state=present
  with_items:
    - ntp
    - ntpdate
    - bridge-utils
    - cgroupfs-mount
    - containerd
    - runc
    - ubuntu-fan
    - apt-transport-https
    - docker.io

- name: Stop ntp service
  service: name=ntp state=stopped enabled=yes
  tags: ntp

- name: Sync ntp service
  shell: ntpdate -s time.nist.gov
  tags: ntp

- name: Start the ntp service
  service: name=ntp state=started enabled=yes
  tags: ntp
