---
# This playbook deploys the Kubernetes cluster with Contrail CNI

# Author: SAVITHRU LOKANATH
# Contact: SAVITHRU AT ICLOUD DOT COM

- name: Bring up kubernetes master
  shell: kubeadm init
  register: output
  tags: master

- debug: msg="{{ output.stdout }}"
